### ISSUE TITLE
Display table results in map

### ISSUE THREAD

**Issue by ThomasThelen** [KnowWhereGraph/kwg-faceted-search#279]
The map should display icons where each thing (hazard, place, expert affiliation) is in the table. When the query or table page changes, the map should refresh. It should also match current functionality where, when then the map icon is clicked, information about that place is given in a tool tip.

@Zhining-ht since you did the map for 1.x, I'm assigning you to this one

**Comment by ThomasThelen** [comment]
What's the status on this issue? I'm noticing that at the moment, the map isn't updating between tab changes.

**Comment by Zhining-ht** [comment]
The locations are still the same as mentioned above. I extracted those locations from the returned text shown above. And also the map can be updated between tab changes.

**Comment by Zhining-ht** [comment]
Place tab does not return locations: 
![Screen Shot 2022-07-16 at 2 58 55 PM](https://user-images.githubusercontent.com/15030443/179373170-5c824356-a417-4d66-a36d-5cb861666d29.png)

locations for Hazard tab: 
![Screen Shot 2022-07-16 at 2 58 35 PM](https://user-images.githubusercontent.com/15030443/179373190-676300f2-405f-43e0-80af-94ada52222fa.png)

locations for Person tab: 
![Screen Shot 2022-07-16 at 2 58 16 PM](https://user-images.githubusercontent.com/15030443/179373181-c92615fa-37e6-453f-88c5-50b5b20052ea.png)

**Comment by ThomasThelen** [comment]
Is sounds like the 'Place' tab might be problematic. Do you need the places returned by the query?

**Comment by Zhining-ht** [comment]
> Is sounds like the 'Place' tab might be the only problematic one. Do you need the places returned by the query?

yeah, right now only the "Place" tab does not return the locations. It will be better if we also get locations for it, but also depends on our user case to decide whether we include it or not.

**Comment by ThomasThelen** [comment]
I think we want to include the places on the map to match the functionality of the existing site. Would you be fine with modifying the SPARQL query to return the place location to finish this issue off?
